/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelinContracts473 from "./openzeppelin-contracts@4.7.3";
export type { openzeppelinContracts473 };
