name: Build application

on:
  push:
    branches: [main, develop]
    tags:
  pull_request:
    branches: [main, develop]
    types: [review_requested, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: NPM install
        run: npm install

      - name: NPM run build
        run: npm run build
