name: Docker

on:
  push:
    branches: [ main, develop ]
    tags:
    - '*'
  pull_request:
    branches:
    - main
    - develop

jobs:
  docker:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u doerfli --password-stdin
      - uses: rlespinasse/github-slug-action@v2.x
      - run: docker build --build-arg INSTANCE=amoy -t ghcr.io/etherisc/depeg-ui/depeg-ui:${{ env.GITHUB_REF_SLUG }} .
      # no push to ghcr.io for now
      # - run: docker push ghcr.io/etherisc/depeg-ui/depeg-ui:${{ env.GITHUB_REF_SLUG }}
